version: "3.1"

services:
  stack_app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    restart: always